# =================================================================
# CONFIGURACOES DO SERVIDOR
# =================================================================
server.port=8080
server.servlet.context-path=/api/v1
spring.application.name=CrediLink
spring.threads.virtual.enabled=true

# =================================================================
# CONFIGURACOES DO BANCO DE DADOS POSTGRESQL
# =================================================================
spring.datasource.url=jdbc:postgresql://${POSTGRES_URL}:${POSTGRES_PORT}/${POSTGRES_NAME}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Pool de conexao
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=600000
spring.datasource.hikari.connection-timeout=60000

# =================================================================
# CONFIGURACOES DO BANCO DE DADOS MARIADB
# =================================================================
sippulse.datasource.url=jdbc:mariadb://${SIPPULSE_HOST_DB}:${SIPPULSE_PORT_DB}/${SIPPULSE_NAME_DB}
sippulse.datasource.username=${SIPPULSE_USERNAME_DB}
sippulse.datasource.password=${SIPPULSE_PASSWORD_DB}
sippulse.datasource.driver-class-name=org.mariadb.jdbc.Driver

# =================================================================
# CONFIGURACOES DA API ITAU
# =================================================================

itau.api.base-url=${ITAU_API_BASE_URL}
itau.api.access-token=${ITAU_URL_API_ACCESS_TOKEN}

itau.client-id=${ITAU_CLIENT_ID}
itau.client-secret=${ITAU_CLIENT_SECRET}

itau.chave.pix=${ITAU_CHAVE_PIX}

itau.ssl.keystore-path=${ITAU_SSL_KEYSTORE_PATH}
itau.ssl.keystore-password=${ITAU_SSL_KEYSTORE_PASSWORD}


# =================================================================
# CONFIGURACOES DO SIPPULSE (WSDL)
# =================================================================

sippulse.ws.url=${SIPPULSE_WS_URL}
sippulse.loginPrincipal=${SIPPULSE_LOGIN_PRINCIPAL}
sippulse.passwordPrincipal=${SIPPULSE_PASSWORD_PRINCIPAL}

# =================================================================
# CONFIGURACOES DO QUARTZ
# =================================================================
spring.quartz.properties.org.quartz.threadPool.threadCount=1
spring.quartz.properties.org.quartz.threadPool.threadPriority=1
spring.quartz.properties.org.quartz.threadPool.class=org.quartz.simpl.SimpleThreadPool

# =================================================================
# CONFIGURACOES DO JWT
# =================================================================

jwt.secret=${JWT_SERCRET}



ixc.api.base-url=${IXC_BASE_URL}



# =================================================================
# CONFIGURACOES DE LOGGING
# =================================================================
logging.level.com.main=DEBUG
logging.level.org.springframework.ws=DEBUG
logging.level.org.hibernate.SQL=INFO
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=INFO
logging.level.com.main.service.WebhookPixService=INFO
logging.level.com.sun.xml.ws=OFF
logging.level.com.sun.xml.ws.policy=OFF
logging.level.com.sun.xml.ws.client=OFF
logging.level.com.sun.xml.internal.ws=OFF
logging.level.java.util.logging.ConsoleHandler=OFF
logging.level.org.hibernate.orm.connections.pooling=WARN
logging.level.com.main.CrediLink.domain.pix.PixService:DEBUG

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.http.client.HttpClientAutoConfiguration