
package com.main.CrediLink.sippulse.wsdlSippulse;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.2
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "SipPulse", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", wsdlLocation = "http://181.191.206.175:8080/SipPulse/SubscriberWS?wsdl")
public class SipPulse
    extends Service
{

    private final static URL SIPPULSE_WSDL_LOCATION;
    private final static WebServiceException SIPPULSE_EXCEPTION;
    private final static QName SIPPULSE_QNAME = new QName("http://service.ws.sippulse.voffice.com.br/", "SipPulse");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://181.191.206.175:8080/SipPulse/SubscriberWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SIPPULSE_WSDL_LOCATION = url;
        SIPPULSE_EXCEPTION = e;
    }

    public SipPulse() {
        super(__getWsdlLocation(), SIPPULSE_QNAME);
    }

    public SipPulse(WebServiceFeature... features) {
        super(__getWsdlLocation(), SIPPULSE_QNAME, features);
    }

    public SipPulse(URL wsdlLocation) {
        super(wsdlLocation, SIPPULSE_QNAME);
    }

    public SipPulse(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SIPPULSE_QNAME, features);
    }

    public SipPulse(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SipPulse(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SubscriberWS
     */
    @WebEndpoint(name = "SubscriberWSPort")
    public SubscriberWS getSubscriberWSPort() {
        return super.getPort(new QName("http://service.ws.sippulse.voffice.com.br/", "SubscriberWSPort"), SubscriberWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SubscriberWS
     */
    @WebEndpoint(name = "SubscriberWSPort")
    public SubscriberWS getSubscriberWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.ws.sippulse.voffice.com.br/", "SubscriberWSPort"), SubscriberWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SIPPULSE_EXCEPTION!= null) {
            throw SIPPULSE_EXCEPTION;
        }
        return SIPPULSE_WSDL_LOCATION;
    }

}
