
package com.main.CrediLink.sippulse.wsdlSippulse;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.2
 * Generated source version: 3.0
 * 
 */
@WebService(name = "SubscriberWS", targetNamespace = "http://service.ws.sippulse.voffice.com.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SubscriberWS {


    /**
     * 
     * @param principal
     * @param subscriber
     * @throws WSException
     */
    @WebMethod
    @RequestWrapper(localName = "updateSubscriber", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.main.CrediLink.sippulse.wsdlSippulse.UpdateSubscriber")
    @ResponseWrapper(localName = "updateSubscriberResponse", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.main.CrediLink.sippulse.wsdlSippulse.UpdateSubscriberResponse")
    public void updateSubscriber(
        @WebParam(name = "subscriber", targetNamespace = "")
        SubscriberDTO subscriber,
        @WebParam(name = "principal", targetNamespace = "")
        UserPrincipalDTO principal)
        throws WSException
    ;

    /**
     * 
     * @param confirmNewPassword
     * @param principal
     * @param domain
     * @param actualPassword
     * @param newPassword
     * @param username
     * @throws WSException
     */
    @WebMethod
    @RequestWrapper(localName = "changePassword", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.main.CrediLink.sippulse.wsdlSippulse.ChangePassword")
    @ResponseWrapper(localName = "changePasswordResponse", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.main.CrediLink.sippulse.wsdlSippulse.ChangePasswordResponse")
    public void changePassword(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "domain", targetNamespace = "")
        String domain,
        @WebParam(name = "actualPassword", targetNamespace = "")
        String actualPassword,
        @WebParam(name = "newPassword", targetNamespace = "")
        String newPassword,
        @WebParam(name = "confirmNewPassword", targetNamespace = "")
        String confirmNewPassword,
        @WebParam(name = "principal", targetNamespace = "")
        UserPrincipalDTO principal)
        throws WSException
    ;

    /**
     * 
     * @param confirmNewPassword
     * @param principal
     * @param domain
     * @param actualPassword
     * @param newPassword
     * @param username
     * @throws WSException
     */
    @WebMethod
    @RequestWrapper(localName = "changePasswordWEB", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.main.CrediLink.sippulse.wsdlSippulse.ChangePasswordWEB")
    @ResponseWrapper(localName = "changePasswordWEBResponse", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.main.CrediLink.sippulse.wsdlSippulse.ChangePasswordWEBResponse")
    public void changePasswordWEB(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "domain", targetNamespace = "")
        String domain,
        @WebParam(name = "actualPassword", targetNamespace = "")
        String actualPassword,
        @WebParam(name = "newPassword", targetNamespace = "")
        String newPassword,
        @WebParam(name = "confirmNewPassword", targetNamespace = "")
        String confirmNewPassword,
        @WebParam(name = "principal", targetNamespace = "")
        UserPrincipalDTO principal)
        throws WSException
    ;

    /**
     * 
     * @param principal
     * @param domain
     * @param newProfileId
     * @param username
     * @throws WSException
     */
    @WebMethod
    @RequestWrapper(localName = "changeProfile", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.main.CrediLink.sippulse.wsdlSippulse.ChangeProfile")
    @ResponseWrapper(localName = "changeProfileResponse", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.main.CrediLink.sippulse.wsdlSippulse.ChangeProfileResponse")
    public void changeProfile(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "domain", targetNamespace = "")
        String domain,
        @WebParam(name = "newProfileId", targetNamespace = "")
        Integer newProfileId,
        @WebParam(name = "principal", targetNamespace = "")
        UserPrincipalDTO principal)
        throws WSException
    ;

    /**
     * 
     * @param principal
     * @param obs
     * @param domain
     * @param value
     * @param username
     * @throws WSException
     */
    @WebMethod
    @RequestWrapper(localName = "addCredit", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.main.CrediLink.sippulse.wsdlSippulse.AddCredit")
    @ResponseWrapper(localName = "addCreditResponse", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.main.CrediLink.sippulse.wsdlSippulse.AddCreditResponse")
    public void addCredit(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "domain", targetNamespace = "")
        String domain,
        @WebParam(name = "value", targetNamespace = "")
        Double value,
        @WebParam(name = "obs", targetNamespace = "")
        String obs,
        @WebParam(name = "principal", targetNamespace = "")
        UserPrincipalDTO principal)
        throws WSException
    ;

    /**
     * 
     * @param principal
     * @param subscriber
     * @return
     *     returns java.lang.Integer
     * @throws WSException
     */
    @WebMethod
    @WebResult(name = "subscriberId", targetNamespace = "")
    @RequestWrapper(localName = "insertSubscriber", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.main.CrediLink.sippulse.wsdlSippulse.InsertSubscriber")
    @ResponseWrapper(localName = "insertSubscriberResponse", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.main.CrediLink.sippulse.wsdlSippulse.InsertSubscriberResponse")
    public Integer insertSubscriber(
        @WebParam(name = "subscriber", targetNamespace = "")
        SubscriberDTO subscriber,
        @WebParam(name = "principal", targetNamespace = "")
        UserPrincipalDTO principal)
        throws WSException
    ;

    /**
     * 
     * @param principal
     * @param domain
     * @param username
     * @throws WSException
     */
    @WebMethod
    @RequestWrapper(localName = "blockCollectCalls", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.main.CrediLink.sippulse.wsdlSippulse.BlockCollectCalls")
    @ResponseWrapper(localName = "blockCollectCallsResponse", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.main.CrediLink.sippulse.wsdlSippulse.BlockCollectCallsResponse")
    public void blockCollectCalls(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "domain", targetNamespace = "")
        String domain,
        @WebParam(name = "principal", targetNamespace = "")
        UserPrincipalDTO principal)
        throws WSException
    ;

    /**
     * 
     * @param principal
     * @param domain
     * @param username
     * @throws WSException
     */
    @WebMethod
    @RequestWrapper(localName = "blockAnonymousCalls", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.main.CrediLink.sippulse.wsdlSippulse.BlockAnonymousCalls")
    @ResponseWrapper(localName = "blockAnonymousCallsResponse", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.main.CrediLink.sippulse.wsdlSippulse.BlockAnonymousCallsResponse")
    public void blockAnonymousCalls(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "domain", targetNamespace = "")
        String domain,
        @WebParam(name = "principal", targetNamespace = "")
        UserPrincipalDTO principal)
        throws WSException
    ;

    /**
     * 
     * @param principal
     * @param domain
     * @param username
     * @throws WSException
     */
    @WebMethod
    @RequestWrapper(localName = "blockEntry0303", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.main.CrediLink.sippulse.wsdlSippulse.BlockEntry0303")
    @ResponseWrapper(localName = "blockEntry0303Response", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.main.CrediLink.sippulse.wsdlSippulse.BlockEntry0303Response")
    public void blockEntry0303(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "domain", targetNamespace = "")
        String domain,
        @WebParam(name = "principal", targetNamespace = "")
        UserPrincipalDTO principal)
        throws WSException
    ;

    /**
     * 
     * @param principal
     * @param domain
     * @param username
     * @throws WSException
     */
    @WebMethod
    @RequestWrapper(localName = "removeSubscriber", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.main.CrediLink.sippulse.wsdlSippulse.RemoveSubscriber")
    @ResponseWrapper(localName = "removeSubscriberResponse", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.main.CrediLink.sippulse.wsdlSippulse.RemoveSubscriberResponse")
    public void removeSubscriber(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "domain", targetNamespace = "")
        String domain,
        @WebParam(name = "principal", targetNamespace = "")
        UserPrincipalDTO principal)
        throws WSException
    ;

    /**
     * 
     * @param principal
     * @param domain
     * @param username
     * @return
     *     returns java.lang.Double
     * @throws WSException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "retrieveCredit", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.main.CrediLink.sippulse.wsdlSippulse.RetrieveCredit")
    @ResponseWrapper(localName = "retrieveCreditResponse", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.main.CrediLink.sippulse.wsdlSippulse.RetrieveCreditResponse")
    public Double retrieveCredit(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "domain", targetNamespace = "")
        String domain,
        @WebParam(name = "principal", targetNamespace = "")
        UserPrincipalDTO principal)
        throws WSException
    ;

    /**
     * 
     * @param principal
     * @param domain
     * @param username
     * @return
     *     returns java.lang.String
     * @throws WSException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "retrievePassword", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.main.CrediLink.sippulse.wsdlSippulse.RetrievePassword")
    @ResponseWrapper(localName = "retrievePasswordResponse", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.main.CrediLink.sippulse.wsdlSippulse.RetrievePasswordResponse")
    public String retrievePassword(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "domain", targetNamespace = "")
        String domain,
        @WebParam(name = "principal", targetNamespace = "")
        UserPrincipalDTO principal)
        throws WSException
    ;

    /**
     * 
     * @param principal
     * @param domain
     * @param username
     * @return
     *     returns java.lang.String
     * @throws WSException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "retrievePasswordWEB", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.main.CrediLink.sippulse.wsdlSippulse.RetrievePasswordWEB")
    @ResponseWrapper(localName = "retrievePasswordWEBResponse", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.main.CrediLink.sippulse.wsdlSippulse.RetrievePasswordWEBResponse")
    public String retrievePasswordWEB(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "domain", targetNamespace = "")
        String domain,
        @WebParam(name = "principal", targetNamespace = "")
        UserPrincipalDTO principal)
        throws WSException
    ;

    /**
     * 
     * @param principal
     * @param subscriber
     * @throws WSException
     */
    @WebMethod
    @RequestWrapper(localName = "updateSubscriberClassV", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.main.CrediLink.sippulse.wsdlSippulse.UpdateSubscriberClassV")
    @ResponseWrapper(localName = "updateSubscriberClassVResponse", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.main.CrediLink.sippulse.wsdlSippulse.UpdateSubscriberClassVResponse")
    public void updateSubscriberClassV(
        @WebParam(name = "subscriber", targetNamespace = "")
        SubscriberClassVDTO subscriber,
        @WebParam(name = "principal", targetNamespace = "")
        UserPrincipalDTO principal)
        throws WSException
    ;

    /**
     * 
     * @param principal
     * @param subscriber
     * @throws WSException
     */
    @WebMethod
    @RequestWrapper(localName = "updateSubscriberBillingInfo", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.main.CrediLink.sippulse.wsdlSippulse.UpdateSubscriberBillingInfo")
    @ResponseWrapper(localName = "updateSubscriberBillingInfoResponse", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.main.CrediLink.sippulse.wsdlSippulse.UpdateSubscriberBillingInfoResponse")
    public void updateSubscriberBillingInfo(
        @WebParam(name = "subscriber", targetNamespace = "")
        SubscriberBillingInfoDTO subscriber,
        @WebParam(name = "principal", targetNamespace = "")
        UserPrincipalDTO principal)
        throws WSException
    ;

    /**
     * 
     * @param principal
     * @param subscriber
     * @throws WSException
     */
    @WebMethod
    @RequestWrapper(localName = "updateSubscriberServices", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.main.CrediLink.sippulse.wsdlSippulse.UpdateSubscriberServices")
    @ResponseWrapper(localName = "updateSubscriberServicesResponse", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.main.CrediLink.sippulse.wsdlSippulse.UpdateSubscriberServicesResponse")
    public void updateSubscriberServices(
        @WebParam(name = "subscriber", targetNamespace = "")
        SubscriberServicesDTO subscriber,
        @WebParam(name = "principal", targetNamespace = "")
        UserPrincipalDTO principal)
        throws WSException
    ;

    /**
     * 
     * @param principal
     * @param domain
     * @param username
     * @return
     *     returns com.main.CrediLink.sippulse.wsdlSippulse.SubscriberDTO
     * @throws WSException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "retrieveSubscriber", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.main.CrediLink.sippulse.wsdlSippulse.RetrieveSubscriber")
    @ResponseWrapper(localName = "retrieveSubscriberResponse", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.main.CrediLink.sippulse.wsdlSippulse.RetrieveSubscriberResponse")
    public SubscriberDTO retrieveSubscriber(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "domain", targetNamespace = "")
        String domain,
        @WebParam(name = "principal", targetNamespace = "")
        UserPrincipalDTO principal)
        throws WSException
    ;

    /**
     * 
     * @param principal
     * @param domain
     * @param username
     * @return
     *     returns com.main.CrediLink.sippulse.wsdlSippulse.SubscriberClassVDTO
     * @throws WSException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "retrieveSubscriberClassV", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.main.CrediLink.sippulse.wsdlSippulse.RetrieveSubscriberClassV")
    @ResponseWrapper(localName = "retrieveSubscriberClassVResponse", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.main.CrediLink.sippulse.wsdlSippulse.RetrieveSubscriberClassVResponse")
    public SubscriberClassVDTO retrieveSubscriberClassV(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "domain", targetNamespace = "")
        String domain,
        @WebParam(name = "principal", targetNamespace = "")
        UserPrincipalDTO principal)
        throws WSException
    ;

    /**
     * 
     * @param principal
     * @param domain
     * @param username
     * @throws WSException
     */
    @WebMethod
    @RequestWrapper(localName = "activateIncommingCalls", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.main.CrediLink.sippulse.wsdlSippulse.ActivateIncommingCalls")
    @ResponseWrapper(localName = "activateIncommingCallsResponse", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.main.CrediLink.sippulse.wsdlSippulse.ActivateIncommingCallsResponse")
    public void activateIncommingCalls(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "domain", targetNamespace = "")
        String domain,
        @WebParam(name = "principal", targetNamespace = "")
        UserPrincipalDTO principal)
        throws WSException
    ;

    /**
     * 
     * @param principal
     * @param domain
     * @param username
     * @throws WSException
     */
    @WebMethod
    @RequestWrapper(localName = "blockIncommingCalls", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.main.CrediLink.sippulse.wsdlSippulse.BlockIncommingCalls")
    @ResponseWrapper(localName = "blockIncommingCallsResponse", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.main.CrediLink.sippulse.wsdlSippulse.BlockIncommingCallsResponse")
    public void blockIncommingCalls(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "domain", targetNamespace = "")
        String domain,
        @WebParam(name = "principal", targetNamespace = "")
        UserPrincipalDTO principal)
        throws WSException
    ;

    /**
     * 
     * @param principal
     * @param domain
     * @param username
     * @throws WSException
     */
    @WebMethod
    @RequestWrapper(localName = "activateOutgoingCalls", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.main.CrediLink.sippulse.wsdlSippulse.ActivateOutgoingCalls")
    @ResponseWrapper(localName = "activateOutgoingCallsResponse", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.main.CrediLink.sippulse.wsdlSippulse.ActivateOutgoingCallsResponse")
    public void activateOutgoingCalls(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "domain", targetNamespace = "")
        String domain,
        @WebParam(name = "principal", targetNamespace = "")
        UserPrincipalDTO principal)
        throws WSException
    ;

    /**
     * 
     * @param principal
     * @param domain
     * @param username
     * @throws WSException
     */
    @WebMethod
    @RequestWrapper(localName = "blockOutgoingCalls", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.main.CrediLink.sippulse.wsdlSippulse.BlockOutgoingCalls")
    @ResponseWrapper(localName = "blockOutgoingCallsResponse", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.main.CrediLink.sippulse.wsdlSippulse.BlockOutgoingCallsResponse")
    public void blockOutgoingCalls(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "domain", targetNamespace = "")
        String domain,
        @WebParam(name = "principal", targetNamespace = "")
        UserPrincipalDTO principal)
        throws WSException
    ;

    /**
     * 
     * @param principal
     * @param domain
     * @param username
     * @throws WSException
     */
    @WebMethod
    @RequestWrapper(localName = "activateCallsOnlyByIp", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.main.CrediLink.sippulse.wsdlSippulse.ActivateCallsOnlyByIp")
    @ResponseWrapper(localName = "activateCallsOnlyByIpResponse", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.main.CrediLink.sippulse.wsdlSippulse.ActivateCallsOnlyByIpResponse")
    public void activateCallsOnlyByIp(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "domain", targetNamespace = "")
        String domain,
        @WebParam(name = "principal", targetNamespace = "")
        UserPrincipalDTO principal)
        throws WSException
    ;

    /**
     * 
     * @param principal
     * @param domain
     * @param username
     * @throws WSException
     */
    @WebMethod
    @RequestWrapper(localName = "blockCallsOnlyByIp", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.main.CrediLink.sippulse.wsdlSippulse.BlockCallsOnlyByIp")
    @ResponseWrapper(localName = "blockCallsOnlyByIpResponse", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.main.CrediLink.sippulse.wsdlSippulse.BlockCallsOnlyByIpResponse")
    public void blockCallsOnlyByIp(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "domain", targetNamespace = "")
        String domain,
        @WebParam(name = "principal", targetNamespace = "")
        UserPrincipalDTO principal)
        throws WSException
    ;

    /**
     * 
     * @param principal
     * @param domain
     * @param username
     * @throws WSException
     */
    @WebMethod
    @RequestWrapper(localName = "activateCollectCalls", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.main.CrediLink.sippulse.wsdlSippulse.ActivateCollectCalls")
    @ResponseWrapper(localName = "activateCollectCallsResponse", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.main.CrediLink.sippulse.wsdlSippulse.ActivateCollectCallsResponse")
    public void activateCollectCalls(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "domain", targetNamespace = "")
        String domain,
        @WebParam(name = "principal", targetNamespace = "")
        UserPrincipalDTO principal)
        throws WSException
    ;

    /**
     * 
     * @param principal
     * @param domain
     * @param username
     * @throws WSException
     */
    @WebMethod
    @RequestWrapper(localName = "activateAnonymousCalls", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.main.CrediLink.sippulse.wsdlSippulse.ActivateAnonymousCalls")
    @ResponseWrapper(localName = "activateAnonymousCallsResponse", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.main.CrediLink.sippulse.wsdlSippulse.ActivateAnonymousCallsResponse")
    public void activateAnonymousCalls(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "domain", targetNamespace = "")
        String domain,
        @WebParam(name = "principal", targetNamespace = "")
        UserPrincipalDTO principal)
        throws WSException
    ;

    /**
     * 
     * @param principal
     * @param domain
     * @param username
     * @throws WSException
     */
    @WebMethod
    @RequestWrapper(localName = "activatePrivacyCalls", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.main.CrediLink.sippulse.wsdlSippulse.ActivatePrivacyCalls")
    @ResponseWrapper(localName = "activatePrivacyCallsResponse", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.main.CrediLink.sippulse.wsdlSippulse.ActivatePrivacyCallsResponse")
    public void activatePrivacyCalls(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "domain", targetNamespace = "")
        String domain,
        @WebParam(name = "principal", targetNamespace = "")
        UserPrincipalDTO principal)
        throws WSException
    ;

    /**
     * 
     * @param principal
     * @param domain
     * @param username
     * @throws WSException
     */
    @WebMethod
    @RequestWrapper(localName = "blockPrivacyCalls", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.main.CrediLink.sippulse.wsdlSippulse.BlockPrivacyCalls")
    @ResponseWrapper(localName = "blockPrivacyCallsResponse", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.main.CrediLink.sippulse.wsdlSippulse.BlockPrivacyCallsResponse")
    public void blockPrivacyCalls(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "domain", targetNamespace = "")
        String domain,
        @WebParam(name = "principal", targetNamespace = "")
        UserPrincipalDTO principal)
        throws WSException
    ;

    /**
     * 
     * @param principal
     * @param lowCreditLimit
     * @param domain
     * @param username
     * @throws WSException
     */
    @WebMethod
    @RequestWrapper(localName = "activateLowCreditNotification", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.main.CrediLink.sippulse.wsdlSippulse.ActivateLowCreditNotification")
    @ResponseWrapper(localName = "activateLowCreditNotificationResponse", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.main.CrediLink.sippulse.wsdlSippulse.ActivateLowCreditNotificationResponse")
    public void activateLowCreditNotification(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "domain", targetNamespace = "")
        String domain,
        @WebParam(name = "lowCreditLimit", targetNamespace = "")
        Double lowCreditLimit,
        @WebParam(name = "principal", targetNamespace = "")
        UserPrincipalDTO principal)
        throws WSException
    ;

    /**
     * 
     * @param principal
     * @param domain
     * @param username
     * @throws WSException
     */
    @WebMethod
    @RequestWrapper(localName = "blockLowCreditNotification", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.main.CrediLink.sippulse.wsdlSippulse.BlockLowCreditNotification")
    @ResponseWrapper(localName = "blockLowCreditNotificationResponse", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.main.CrediLink.sippulse.wsdlSippulse.BlockLowCreditNotificationResponse")
    public void blockLowCreditNotification(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "domain", targetNamespace = "")
        String domain,
        @WebParam(name = "principal", targetNamespace = "")
        UserPrincipalDTO principal)
        throws WSException
    ;

    /**
     * 
     * @param principal
     * @param domain
     * @param username
     * @throws WSException
     */
    @WebMethod
    @RequestWrapper(localName = "activateDailyStatistics", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.main.CrediLink.sippulse.wsdlSippulse.ActivateDailyStatistics")
    @ResponseWrapper(localName = "activateDailyStatisticsResponse", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.main.CrediLink.sippulse.wsdlSippulse.ActivateDailyStatisticsResponse")
    public void activateDailyStatistics(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "domain", targetNamespace = "")
        String domain,
        @WebParam(name = "principal", targetNamespace = "")
        UserPrincipalDTO principal)
        throws WSException
    ;

    /**
     * 
     * @param principal
     * @param domain
     * @param username
     * @throws WSException
     */
    @WebMethod
    @RequestWrapper(localName = "blockDailyStatistics", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.main.CrediLink.sippulse.wsdlSippulse.BlockDailyStatistics")
    @ResponseWrapper(localName = "blockDailyStatisticsResponse", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.main.CrediLink.sippulse.wsdlSippulse.BlockDailyStatisticsResponse")
    public void blockDailyStatistics(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "domain", targetNamespace = "")
        String domain,
        @WebParam(name = "principal", targetNamespace = "")
        UserPrincipalDTO principal)
        throws WSException
    ;

    /**
     * 
     * @param principal
     * @param dailyQuotaDTO
     * @throws WSException
     */
    @WebMethod
    @RequestWrapper(localName = "updateDailyQuota", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.main.CrediLink.sippulse.wsdlSippulse.UpdateDailyQuota")
    @ResponseWrapper(localName = "updateDailyQuotaResponse", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.main.CrediLink.sippulse.wsdlSippulse.UpdateDailyQuotaResponse")
    public void updateDailyQuota(
        @WebParam(name = "dailyQuotaDTO", targetNamespace = "")
        SubscriberDailyQuotaDTO dailyQuotaDTO,
        @WebParam(name = "principal", targetNamespace = "")
        UserPrincipalDTO principal)
        throws WSException
    ;

    /**
     * 
     * @param principal
     * @param domain
     * @param username
     * @throws WSException
     */
    @WebMethod
    @RequestWrapper(localName = "activateSubscriber", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.main.CrediLink.sippulse.wsdlSippulse.ActivateSubscriber")
    @ResponseWrapper(localName = "activateSubscriberResponse", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.main.CrediLink.sippulse.wsdlSippulse.ActivateSubscriberResponse")
    public void activateSubscriber(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "domain", targetNamespace = "")
        String domain,
        @WebParam(name = "principal", targetNamespace = "")
        UserPrincipalDTO principal)
        throws WSException
    ;

    /**
     * 
     * @param principal
     * @param domain
     * @param voicemailPassword
     * @param username
     * @throws WSException
     */
    @WebMethod
    @RequestWrapper(localName = "activateVoicemail", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.main.CrediLink.sippulse.wsdlSippulse.ActivateVoicemail")
    @ResponseWrapper(localName = "activateVoicemailResponse", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.main.CrediLink.sippulse.wsdlSippulse.ActivateVoicemailResponse")
    public void activateVoicemail(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "domain", targetNamespace = "")
        String domain,
        @WebParam(name = "voicemailPassword", targetNamespace = "")
        Long voicemailPassword,
        @WebParam(name = "principal", targetNamespace = "")
        UserPrincipalDTO principal)
        throws WSException
    ;

    /**
     * 
     * @param principal
     * @param domain
     * @param username
     * @throws WSException
     */
    @WebMethod
    @RequestWrapper(localName = "blockVoicemail", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.main.CrediLink.sippulse.wsdlSippulse.BlockVoicemail")
    @ResponseWrapper(localName = "blockVoicemailResponse", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.main.CrediLink.sippulse.wsdlSippulse.BlockVoicemailResponse")
    public void blockVoicemail(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "domain", targetNamespace = "")
        String domain,
        @WebParam(name = "principal", targetNamespace = "")
        UserPrincipalDTO principal)
        throws WSException
    ;

    /**
     * 
     * @param principal
     * @param domain
     * @param username
     * @throws WSException
     */
    @WebMethod
    @RequestWrapper(localName = "blockSubscriber", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.main.CrediLink.sippulse.wsdlSippulse.BlockSubscriber")
    @ResponseWrapper(localName = "blockSubscriberResponse", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.main.CrediLink.sippulse.wsdlSippulse.BlockSubscriberResponse")
    public void blockSubscriber(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "domain", targetNamespace = "")
        String domain,
        @WebParam(name = "principal", targetNamespace = "")
        UserPrincipalDTO principal)
        throws WSException
    ;

    /**
     * 
     * @param principal
     * @param monthlyQuotaDTO
     * @throws WSException
     */
    @WebMethod
    @RequestWrapper(localName = "updateMonthlyQuota", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.main.CrediLink.sippulse.wsdlSippulse.UpdateMonthlyQuota")
    @ResponseWrapper(localName = "updateMonthlyQuotaResponse", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.main.CrediLink.sippulse.wsdlSippulse.UpdateMonthlyQuotaResponse")
    public void updateMonthlyQuota(
        @WebParam(name = "monthlyQuotaDTO", targetNamespace = "")
        SubscriberMonthlyQuotaDTO monthlyQuotaDTO,
        @WebParam(name = "principal", targetNamespace = "")
        UserPrincipalDTO principal)
        throws WSException
    ;

    /**
     * 
     * @param principal
     * @param domain
     * @param username
     * @return
     *     returns com.main.CrediLink.sippulse.wsdlSippulse.SubscriberDailyQuotaDTO
     * @throws WSException
     */
    @WebMethod
    @WebResult(name = "dailyQuotaDTO", targetNamespace = "")
    @RequestWrapper(localName = "retrieveDailyQuota", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.main.CrediLink.sippulse.wsdlSippulse.RetrieveDailyQuota")
    @ResponseWrapper(localName = "retrieveDailyQuotaResponse", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.main.CrediLink.sippulse.wsdlSippulse.RetrieveDailyQuotaResponse")
    public SubscriberDailyQuotaDTO retrieveDailyQuota(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "domain", targetNamespace = "")
        String domain,
        @WebParam(name = "principal", targetNamespace = "")
        UserPrincipalDTO principal)
        throws WSException
    ;

    /**
     * 
     * @param principal
     * @param domain
     * @param username
     * @return
     *     returns com.main.CrediLink.sippulse.wsdlSippulse.SubscriberMonthlyQuotaDTO
     * @throws WSException
     */
    @WebMethod
    @WebResult(name = "monthlyQuotaDTO", targetNamespace = "")
    @RequestWrapper(localName = "retrieveMonthlyQuotaDTO", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.main.CrediLink.sippulse.wsdlSippulse.RetrieveMonthlyQuotaDTO")
    @ResponseWrapper(localName = "retrieveMonthlyQuotaDTOResponse", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.main.CrediLink.sippulse.wsdlSippulse.RetrieveMonthlyQuotaDTOResponse")
    public SubscriberMonthlyQuotaDTO retrieveMonthlyQuotaDTO(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "domain", targetNamespace = "")
        String domain,
        @WebParam(name = "principal", targetNamespace = "")
        UserPrincipalDTO principal)
        throws WSException
    ;

    /**
     * 
     * @param principal
     * @param domain
     * @param username
     * @throws WSException
     */
    @WebMethod
    @RequestWrapper(localName = "activateSoftphone", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.main.CrediLink.sippulse.wsdlSippulse.ActivateSoftphone")
    @ResponseWrapper(localName = "activateSoftphoneResponse", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.main.CrediLink.sippulse.wsdlSippulse.ActivateSoftphoneResponse")
    public void activateSoftphone(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "domain", targetNamespace = "")
        String domain,
        @WebParam(name = "principal", targetNamespace = "")
        UserPrincipalDTO principal)
        throws WSException
    ;

    /**
     * 
     * @param principal
     * @param domain
     * @param username
     * @throws WSException
     */
    @WebMethod
    @RequestWrapper(localName = "blockSoftphone", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.main.CrediLink.sippulse.wsdlSippulse.BlockSoftphone")
    @ResponseWrapper(localName = "blockSoftphoneResponse", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.main.CrediLink.sippulse.wsdlSippulse.BlockSoftphoneResponse")
    public void blockSoftphone(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "domain", targetNamespace = "")
        String domain,
        @WebParam(name = "principal", targetNamespace = "")
        UserPrincipalDTO principal)
        throws WSException
    ;

    /**
     * 
     * @param principal
     * @param domain
     * @param username
     * @throws WSException
     */
    @WebMethod
    @RequestWrapper(localName = "activateEntry0303", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.main.CrediLink.sippulse.wsdlSippulse.ActivateEntry0303")
    @ResponseWrapper(localName = "activateEntry0303Response", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.main.CrediLink.sippulse.wsdlSippulse.ActivateEntry0303Response")
    public void activateEntry0303(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "domain", targetNamespace = "")
        String domain,
        @WebParam(name = "principal", targetNamespace = "")
        UserPrincipalDTO principal)
        throws WSException
    ;

    /**
     * 
     * @param principal
     * @param domain
     * @param username
     * @throws WSException
     */
    @WebMethod
    @RequestWrapper(localName = "disableValidateSource0303", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.main.CrediLink.sippulse.wsdlSippulse.DisableValidateSource0303")
    @ResponseWrapper(localName = "disableValidateSource0303Response", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.main.CrediLink.sippulse.wsdlSippulse.DisableValidateSource0303Response")
    public void disableValidateSource0303(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "domain", targetNamespace = "")
        String domain,
        @WebParam(name = "principal", targetNamespace = "")
        UserPrincipalDTO principal)
        throws WSException
    ;

    /**
     * 
     * @param principal
     * @param domain
     * @param username
     * @throws WSException
     */
    @WebMethod
    @RequestWrapper(localName = "activateValidateSource0303", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.main.CrediLink.sippulse.wsdlSippulse.ActivateValidateSource0303")
    @ResponseWrapper(localName = "activateValidateSource0303Response", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.main.CrediLink.sippulse.wsdlSippulse.ActivateValidateSource0303Response")
    public void activateValidateSource0303(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "domain", targetNamespace = "")
        String domain,
        @WebParam(name = "principal", targetNamespace = "")
        UserPrincipalDTO principal)
        throws WSException
    ;

}
